version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.1
  golang-ci: epavlova/golang-ci@<<pipeline.parameters.dev-orb-version>>

deploy_tags_and_branches: &deploy_tags_and_branches
  tags:
    only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/

deploy_only_tags: &deploy_only_tags
  branches:
    ignore: /.*/
  tags:
    only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/

parameters:
  dev-orb-version:
    default: dev:alpha
    type: string
  run-integration-tests:
    type: boolean
    default: false

workflows:
  lint_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint:
          filters: *deploy_tags_and_branches

      - orb-tools/pack:
          requires:
            - orb-tools/lint
          filters: *deploy_tags_and_branches

      - orb-tools/publish-dev:
          orb-name: epavlova/golang-ci
          context: publish-orbs
          publish-sha-version: true
          requires:
            - orb-tools/pack
          filters: *deploy_tags_and_branches

      - orb-tools/trigger-integration-tests-workflow:
          context: publish-orbs
          requires:
            - orb-tools/publish-dev
          filters: *deploy_tags_and_branches

  integration-test_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # the following jobs act as integrations tests for this orb, we run them and expect not to error
      # they should use the just published dev:alpha version
      - golang-ci/build-and-test:
          name: default-integration-tests
          filters: *deploy_tags_and_branches

      - golang-ci/docker-build:
          name: docker-job-integration-tests
          filters: *deploy_tags_and_branches

      - orb-tools/dev-promote-prod-from-git-tag:
          orb-name: epavlova/golang-ci
          context: publish-orbs
          add-pr-comment: false
          perform-branch-check: false
          requires:
            - default-integration-tests
            - docker-job-integration-tests
          filters: *deploy_only_tags
