version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  golang-ci: epavlova/golang-ci@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests:
    type: boolean
    default: false

workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: epavlova/golang-ci
          context: publish-orbs
          publish-sha-version: true
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: publish-orbs
          requires:
            - orb-tools/publish-dev

  prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # the following jobs act as integrations tests for this orb, we run them and expect not to error
      # they should use the just published dev:alpha version
#      - golang-ci/build-and-test:
#          name: default-integration-tests
#
#      - golang-ci/docker-build:
#          name: docker-job-integration-tests

      - orb-tools/dev-promote-prod-from-git-tag:
          orb-name: epavlova/golang-ci
          context: publish-orbs
          add-pr-comment: false
          perform-branch-check: false
#          requires:
#            - default-integration-tests
#            - docker-job-integration-tests
          filters:
            branches:
              ignore: /.*/
#            tags:
#              only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/
